Repository nanoframework/metadata-processor, pull requests merged in 2020-02, with the labels that each got.

#41 Several fixes in signature generation
  source/MetadataProcessor.Core/Tables/nanoSignaturesTable.cs
  source/MetadataProcessor.Core/Utility/NativeMethodsCrc.cs
  source/MetadataProcessor.Core/Utility/nanoCLR_DataType.cs
  source/MetadataProcessor.Core/Utility/nanoSerializationType.cs
  source/MetadataProcessor.Core/nanoDumperGenerator.cs
  source/native/Tools.Parser/AssemblyParserDump.cpp
Labels: Type: bug

#42 Improvements in attributes exclusion
  source/MetadataProcessor.Core/DumpGenerator/DumpTemplates.cs
  source/MetadataProcessor.Core/Extensions/TypeDefinitionExtensions.cs
  source/MetadataProcessor.Core/Tables/nanoTablesContext.cs
  source/MetadataProcessor.Core/Tables/nanoTypeDefinitionTable.cs
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
  source/MetadataProcessor.Core/nanoDumperGenerator.cs
  source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
Labels: Type: enhancement

#43 Fix type references processing
  source/MetadataProcessor.Console/Program.cs
  source/MetadataProcessor.Core/Tables/nanoTablesContext.cs
  source/MetadataProcessor.Core/Tables/nanoTypeReferenceTable.cs
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
  source/MetadataProcessor.Core/nanoDumperGenerator.cs
Labels: Type: bug

#45 Fix signature generation
  source/MetadataProcessor.Core/Tables/nanoTablesContext.cs
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
Labels: Type: bug

#46 Add missing type ref processing on method body
  source/MetadataProcessor.Console/Program.cs
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
Labels: Type: bug

#47 Fix minimize of FieldDefs
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
Labels: Type: bug

#48 Fix in minimize processing Member refs and fields
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
Labels: Type: bug

#49 Several fixes with minimization workflow
  source/MetadataProcessor.Core/Extensions/TypeReferenceExtensions.cs
  source/MetadataProcessor.Core/MetadataProcessor.Core.csproj
  source/MetadataProcessor.Core/Tables/nanoTablesContext.cs
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
Labels: Type: bug

#50 Improvements dump metadata generator
  source/MetadataProcessor.Core/DumpGenerator/AttributeCustom.cs
  source/MetadataProcessor.Core/DumpGenerator/DumpAllTable.cs
  source/MetadataProcessor.Core/DumpGenerator/DumpTemplates.cs
  source/MetadataProcessor.Core/MetadataProcessor.Core.csproj
  source/MetadataProcessor.Core/nanoDumperGenerator.cs
  source/native/Tools.Parser/AssemblyParserDump.cpp
Labels: Type: enhancement

#51 Fixes in method signature generator
  source/MetadataProcessor.Core/Tables/nanoByteCodeTable.cs
  source/MetadataProcessor.Core/Tables/nanoSignaturesTable.cs
Labels: Type: bug

#52 Improvements in minimize stage when cleaning the string table
  source/MetadataProcessor.Core/Tables/nanoStringTable.cs
  source/MetadataProcessor.Core/Tables/nanoTablesContext.cs
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
Labels: Type: bug

#53 Work refs version
  source/MetadataProcessor.Console/MetadataProcessor.Console.csproj
  source/MetadataProcessor.Console/app.config
  source/MetadataProcessor.Core/MetadataProcessor.Core.csproj
  source/MetadataProcessor.Core/app.config
  source/MetadataProcessor.Core/package.nuspec
  source/MetadataProcessor.Core/packages.config
  source/nanoFramework.Tools.MetadataProcessor.sln
  source/version.json
Labels: Type: dependencies

#54 Replace template generator
  source/MetadataProcessor.Core/DumpGenerator/DumpAllTable.cs
  source/MetadataProcessor.Core/DumpGenerator/DumpTemplates.cs
  source/MetadataProcessor.Core/MetadataProcessor.Core.csproj
  source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs
  source/MetadataProcessor.Core/nanoDependencyGenerator.cs
  source/MetadataProcessor.Core/nanoDumperGenerator.cs
  source/MetadataProcessor.Core/nanoFramework.Tools.MetaDataProcessor.Core.targets
  source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
  source/MetadataProcessor.Core/package.nuspec
  source/MetadataProcessor.Core/packages.config
  source/version.json
Labels: Type: enhancement

#55 Fix minimize processing for enum parameters
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
Labels: Type: bug

#56 Rework string table minimization
  source/MetadataProcessor.Core/Tables/nanoByteCodeTable.cs
  source/MetadataProcessor.Core/Tables/nanoStringTable.cs
  source/MetadataProcessor.Core/Tables/nanoTablesContext.cs
  source/MetadataProcessor.Core/nanoDumperGenerator.cs
  source/version.json
Labels: Type: enhancement

#57 Add support for Interop stubs generation
  source/MetadataProcessor.Console/Program.cs
  source/MetadataProcessor.Core/Extensions/ParameterDefintionExtensions.cs
  source/MetadataProcessor.Core/Extensions/TypeReferenceExtensions.cs
  source/MetadataProcessor.Core/MetadataProcessor.Core.csproj
  source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClass.cs
  source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClassStubs.cs
  source/MetadataProcessor.Core/SkeletonGenerator/AssemblyLookupTable.cs
  source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs
  source/MetadataProcessor.Core/nanoDumperGenerator.cs
  source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
  source/version.json
Labels: Type: enhancement

#59 Improve skeleton generator
  source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClassTable.cs
  source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs
  source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
Labels: Type: enhancement

#60 Add check for missing AssemblyNativeVersionAttribute
  source/MetadataProcessor.Console/Program.cs
  source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
Labels: Type: enhancement

#61 Update target famework to 4.7.2
  source/MetadataProcessor.Console/MetadataProcessor.Console.csproj
  source/MetadataProcessor.Console/app.config
  source/MetadataProcessor.Core/MetadataProcessor.Core.csproj
  source/version.json
Labels: Type: enhancement

#62 Fix parameterIndex increment in skeleton generator for Interop
  source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
Labels: Type: bug

#63 Fix marshalling declaration using CLR types in skeleton generator
  source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
Labels: Type: bug

#64 CRC32 for native methods is now always updated
  source/MetadataProcessor.Core/nanoAssemblyDefinition.cs
Labels: Type: bug

#65 Fix edge case in minimization step for referenced enum types
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
Labels: Type: bug

#66 Fix minimize step for resources
  source/MetadataProcessor.Core/Tables/nanoStringTable.cs
  source/MetadataProcessor.Core/Tables/nanoTablesContext.cs
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
Labels: Type: bug

#67 Add processing to update native methods CRC32
  source/MetadataProcessor.Core/nanoAssemblyDefinition.cs
Labels: Breaking-Change, Type: enhancement

#68 Fix issue with nested types
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
Labels: Type: bug
