Repository nanoframework/metadata-processor, pull requests merged in 2020-12, with the labels that each got.

#121 Add support to process methods with generics <T> in parameters and as return type
  MetadataProcessor.Core/Extensions/MethodDefinitionExtensions.cs
  MetadataProcessor.Core/Extensions/TypeReferenceExtensions.cs
  MetadataProcessor.Core/MetadataProcessor.Core.csproj
  MetadataProcessor.Core/Tables/nanoSignaturesTable.cs
  MetadataProcessor.Core/Utility/NativeMethodsCrc.cs
  MetadataProcessor.Core/Utility/nanoCLR_DataType.cs
  MetadataProcessor.Core/nanoDumperGenerator.cs
Labels: CI: Update Dependents, Type: enhancement

#122 Preserve DataType for Generic Instance
  MetadataProcessor.Core/Tables/nanoSignaturesTable.cs
Labels: CI: Update Dependents, Type: enhancement

#123 Remove DATATYPE_GENERIC
  MetadataProcessor.Core/Tables/nanoSignaturesTable.cs
  MetadataProcessor.Core/Utility/nanoCLR_DataType.cs
Labels: Type: bug

#125 Update Mono.Cecil to 0.11.3
  MetadataProcessor.Console/MetadataProcessor.Console.csproj
  MetadataProcessor.Core/MetadataProcessor.Core.csproj
  MetadataProcessor.Core/packages.lock.json
Labels: Type: dependencies

#124 Work on adding support for generics
  MetadataProcessor.Core/DumpGenerator/DumpTemplates.cs
  MetadataProcessor.Core/DumpGenerator/GenericParam.cs
  MetadataProcessor.Core/DumpGenerator/TypeDef.cs
  MetadataProcessor.Core/Extensions/TypeReferenceExtensions.cs
  MetadataProcessor.Core/MetadataProcessor.Core.csproj
  MetadataProcessor.Core/Tables/nanoGenericParamTable.cs
  MetadataProcessor.Core/Tables/nanoSignaturesTable.cs
  MetadataProcessor.Core/Tables/nanoTablesContext.cs
  MetadataProcessor.Core/nanoAssemblyBuilder.cs
  MetadataProcessor.Core/nanoDumperGenerator.cs
  MetadataProcessor.Core/nanoSkeletonGenerator.cs
  nanoFramework.Tools.MetadataProcessor.sln
  version.json
Labels: CI: Update Dependents, Type: enhancement

#126 Work adding support for generics
  MetadataProcessor.Core/Tables/nanoSignaturesTable.cs
  MetadataProcessor.Core/Utility/nanoCLR_DataType.cs
  MetadataProcessor.Core/nanoAssemblyBuilder.cs
  version.json
Labels: CI: Update Dependents, Type: bug, Type: enhancement

#127 Add processing of field ref and method ref to support generics
  MetadataProcessor.Core/Tables/nanoFieldReferenceTable.cs
  MetadataProcessor.Core/Tables/nanoMethodReferenceTable.cs
  MetadataProcessor.Core/nanoAssemblyBuilder.cs
Labels: CI: Update Dependents, Type: enhancement

#128 Add MSBuild task with MDP
  MetadataProcessor.MsBuildTask/MetaDataProcessorTask.cs
  MetadataProcessor.MsBuildTask/MetadataProcessor.MsBuildTask.csproj
  MetadataProcessor.MsBuildTask/Properties/AssemblyInfo.cs
  MetadataProcessor.MsBuildTask/TasksConstants.cs
  MetadataProcessor.MsBuildTask/Utilities/DebuggerHelper.cs
  MetadataProcessor.MsBuildTask/nanoFramework.Tools.MetadataProcessor.MsBuildTask.targets
  MetadataProcessor.MsBuildTask/package.nuspec
  MetadataProcessor.MsBuildTask/packages.lock.json
  azure-pipelines.yml
  azure-pipelines/update-dependencies.ps1
  nanoFramework.Tools.MetadataProcessor.sln
  version.json
Labels: Type: enhancement

#129 Fix processing of generic type
  MetadataProcessor.Core/Tables/nanoMethodDefinitionTable.cs
  MetadataProcessor.Core/Tables/nanoSignaturesTable.cs
Labels: CI: Update Dependents, Type: bug
