Repository nanoframework/metadata-processor, pull requests merged in 2020-04, with the labels that each got.

#84 Fix checking for class inclusion in typedef extension
  source/MetadataProcessor.Core/Extensions/TypeDefinitionExtensions.cs
Labels: Type: bug

#85 Fix minimize of Method return type
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
Labels: Type: bug

#86 Fix processing of array parameter type in method minimization
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
Labels: Type: bug

#87 Fix signature generator for array elements
  source/MetadataProcessor.Core/Tables/nanoSignaturesTable.cs
Labels: CI: Update Dependents, Type: bug

#88 Fix minize step for CustomAttributes in dependency collection
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
Labels: Type: bug

#89 Fix TypeRef ID calculation for TypeSpec entry
  source/MetadataProcessor.Core/Mono.Cecil/CodeWriter.cs
Labels: Type: bug

#90 Fix output of TypeRef dump
  source/MetadataProcessor.Core/nanoDumperGenerator.cs
Labels: Type: bug

#91 Fix native type for data types I4 and U4 (to match native declarations)
  source/MetadataProcessor.Core/Extensions/TypeReferenceExtensions.cs
Labels: CI: Update Dependents, Type: bug

#92 SkeletonTemplates: Removing useless whitespaces
  source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs
Labels: Type: dependencies

#93 Fix custom attributes processing
  source/MetadataProcessor.Core/DumpGenerator/AttFixedArgs.cs
  source/MetadataProcessor.Core/DumpGenerator/AttributeCustom.cs
  source/MetadataProcessor.Core/DumpGenerator/DumpTemplates.cs
  source/MetadataProcessor.Core/Extensions/TypeReferenceExtensions.cs
  source/MetadataProcessor.Core/MetadataProcessor.Core.csproj
  source/MetadataProcessor.Core/Tables/nanoMethodDefinitionTable.cs
  source/MetadataProcessor.Core/nanoDumperGenerator.cs
Labels: Type: bug

#94 Fix processing dump output in custom attributes
  source/MetadataProcessor.Core/DumpGenerator/DumpTemplates.cs
  source/MetadataProcessor.Core/nanoDumperGenerator.cs
Labels: CI: Update Dependents, Type: bug
