Repository nanoframework/metadata-processor, pull requests merged in 2020-05, with the labels that each got.

#95 SkeletonTemplates: Tweaking the formatting a bit
  source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs
Labels: Type: enhancement

#96 Fix assembly resolution
  source/MetadataProcessor.Core/Utility/LoadHintsAssemblyResolver.cs
Labels: Breaking-Change, Type: bug

#97 Fix indexing of class fields for derived classes
  source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
Labels: Type: bug

#98 Fix CMake module generator
  source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClass.cs
  source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClassTable.cs
  source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs
  source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
Labels: Type: bug

#99 Managed enums are now exported to class declaration
  source/MetadataProcessor.Core/Extensions/TypeDefinitionExtensions.cs
  source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClass.cs
  source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs
  source/MetadataProcessor.Core/Tables/nanoTypeDefinitionTable.cs
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
  source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
  source/version.json
Labels: CI: Update Dependents, Type: enhancement

#100 Improve enum export code
  source/MetadataProcessor.Core/Extensions/TypeDefinitionExtensions.cs
  source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClass.cs
  source/MetadataProcessor.Core/SkeletonGenerator/SkeletonTemplates.cs
  source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
Labels: Type: enhancement

#101 Improvements in enum export
  source/MetadataProcessor.Core/Extensions/TypeDefinitionExtensions.cs
  source/MetadataProcessor.Core/SkeletonGenerator/AssemblyClass.cs
  source/MetadataProcessor.Core/nanoSkeletonGenerator.cs
Labels: CI: Update Dependents, Type: enhancement

#102 Fix enum exported when namespaces aren't correctly processed
  source/MetadataProcessor.Core/Extensions/TypeDefinitionExtensions.cs
Labels: Type: bug

#103 Fix processing of method exception handlers
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
  source/MetadataProcessor.Core/nanoDumperGenerator.cs
Labels: Type: bug

#104 Fix primitive datatypes
  source/MetadataProcessor.Core/Tables/nanoSignaturesTable.cs
Labels: Type: bug

#105 Fix exception processing when there is only finally
  source/MetadataProcessor.Core/nanoAssemblyBuilder.cs
  source/MetadataProcessor.Core/nanoDumperGenerator.cs
Labels: CI: Update Dependents, Type: bug

#106 Improve handling of exceptions in typos dumper code
  source/MetadataProcessor.Core/nanoDumperGenerator.cs
Labels: CI: Update Dependents, Type: bug
